### ISSUE TITLE
[STORY] As a medical admin professional I want to browse existent forms to reuse them or to know which forms are there

### ISSUE THREAD

**Issue by guilhermeramirezeld** [AndreisPurim/MC426#39]
Acceptance criteria:

- [ ] search by name
- [ ] search by form field
- [ ] search by creation date
