### ISSUE TITLE
[STORY] As a doctor, I want to visualize my medical information, so I can check and edit those informations

### ISSUE THREAD

**Issue by guilhermeramirezeld** [AndreisPurim/MC426#43]
Acceptatioin criteria:
- [ ] verify if the user can see their information
- [ ] verify if the user can edit their information
- [ ] verify if the user can save edited information
