### ISSUE TITLE
[STORY] As a doctor, I want to input my patients' information in online formularies, including specific details for different computer radiography (CR) exams, so I can generate accurate and tailored QR Codes representing computer radiography for each patient.

### ISSUE THREAD

**Issue by VictorScholze** [AndreisPurim/MC426#44]
Acceptatioin criteria:
- [ ] verify if the QR code is being generated
- [ ] verify if the user can input specific details
- [ ] verify if the user can input patient information
