### ISSUE TITLE
[Epic 1 - Story 2] Editing

### ISSUE THREAD

**Issue by AndreisPurim** [AndreisPurim/MC426#48]
**Story:** As a doctor, I want to visualize my medical information, so I can check and edit my data.

**Acceptance criteria:**

- [ ] Verify if the user can see their information
- [ ] Verify if the user can edit their information
- [ ] Verify if the user can save edited information

**Comment by brenofranca83** [comment]
Não é verificar se ele pode "ver". Isso é um teste de oftalmo =P
Ainda, notem que vocês estão colocando a responsabilidade da história estar correta na existência de outras funções (potenciais histórias): see, edit, save. Isso torna automaticamente essa história dependente das outras.
