### ISSUE TITLE
[Epic 2 - Story 2] Form creation

### ISSUE THREAD

**Issue by AndreisPurim** [AndreisPurim/MC426#51]
**Story:** As a doctor, I want to be able to create a medical form that generates a medical report and set it public for other doctors to use.

**Acceptance Criteria:**
- [ ] Verify if question creation appends new questions to form
- [ ] Verify if form data is being stored
- [ ] Verify if form data is published on the search table
