### ISSUE TITLE
[Epic 3 - Story 1] Form Use

### ISSUE THREAD

**Issue by AndreisPurim** [AndreisPurim/MC426#54]
**Story:** As a doctor, I want to be able to input a certain patient's data within the appropriate form to generate a medical report.

**Acceptance Criteria:**

- [ ] Verify if the doctor can select forms to be used
- [ ] Verify if the software enforces input types
- [ ] Verify if the user data generates the medical report
