### ISSUE TITLE
[Epic 3 - Story 2] Extracting data from QR Code

### ISSUE THREAD

**Issue by AndreisPurim** [AndreisPurim/MC426#55]
**Story:** As a doctor, I want to be able to extract information from a patient's QR Code information, recreating a previous forms if necessary.

- [ ] Verify if QR Code reader is working
- [ ] Verify if reader recreates information in QR Code
- [ ] Verify if user can access the previous forms
