### ISSUE TITLE
[Epic 3 - Story 3] Editable Medical Report

### ISSUE THREAD

**Issue by AndreisPurim** [AndreisPurim/MC426#56]
**Story:** As a doctor, I want that the information in a filled forms about a patient generates a pre-written, editable Medical Report with a QR Code and my doctor's information, so I can print and deliver the report to a patient

**Acceptance Criteria:**
- [ ] Verify if QR Code is generating
- [ ] Verify if pre-written text is generating with patient information
- [ ] Verify if downloadable file is editable.
